// All user-facing brand strings live here so the vocabulary stays consistent.
export const copy = {
  appName: 'Chromasome',
  brand: 'In My DNA',
  brandUrl: 'https://inmydna.com',
  brandHost: 'inmydna.com',
  coffee: 'Buy me a coffee',
  coffeeUrl: 'https://buymeacoffee.com/inmydna',

  mutate: 'Mutate',
  mutateHint: 'Press space',
  lock: 'Lock',
  unlock: 'Unlock',
  strand: 'strand',
  extractPhoto: 'Extract from photo',
  colorCode: 'Color code',
  export: 'Export',
  undo: 'Undo',
  redo: 'Redo',
  adjust: 'Adjust',
  remove: 'Remove',
  add: 'Add color',
  moveLeft: 'Move left',
  moveRight: 'Move right',
  moveUp: 'Move up',
  moveDown: 'Move down',
  drag: 'Drag to reorder',

  toastCopiedHex: (hex: string) => `Copied ${hex}`,
  toastCopiedCode: 'Color code copied',
  toastCopied: 'Copied',
  toastDownloaded: 'Downloaded',
  toastBadImage: 'That file is not an image',
  toastImageTooBig: 'Image is too big (max 20 MB)',
  toastExtractFailed: 'Could not read that image',

  useStrand: 'Use this strand',
  dropImage: 'Drop an image here or click to choose one',
  extracting: 'Reading the photo…',

  more: 'More actions',
  checksTitle: 'Palette checks',
  checksSummary: (passed: number, total: number) => `${passed} of ${total} checks pass`,
  squint: 'Squint',
  proportional: 'Size board by role',
  dontShowAgain: 'Don’t show again',
  closeChecks: 'Close checks',
  checkStatus: { pass: 'Pass', warn: 'Almost', fail: 'Fail' },
  pngLayout: 'PNG layout',
  checkTitles: {
    emphasis: 'One loud, the rest quiet',
    value: 'Dark, middle and light',
    space: 'Loud takes the least space',
  },
  roleLabels: {
    background: 'Background',
    second: 'Second',
    loud: 'Loud',
    accent: 'Accent',
    extra: 'Extra',
  },
  verdicts: {
    oneLoud: (loud: string) => `${loud} leads and the rest stay quiet.`,
    calm: 'Calm palette: nothing shouts, so lightness does the work.',
    halfLoud: (hex: string) => `${hex} is half-loud. Mute it or let it lead.`,
    shouting: (hexes: string[]) =>
      hexes.length === 2 ? `${hexes[0]} and ${hexes[1]} are both shouting. Mute one.` : `${hexes.length} colors are shouting. Keep one loud.`,
    distinct: 'Dark, middle and light stay apart in greyscale.',
    pairApart: 'The two colors stay apart in greyscale.',
    anchored: (hex: string) => `Two sit close, but ${hex} stands well apart, so it still reads.`,
    close: (a: string, b: string) => `${a} and ${b} sit close in value. Push one lighter or darker.`,
    blur: 'Squint and these blur together. Push one lighter or darker.',
    pops: (loud: string, share: number) => `${loud} pops. Give it the least space, about ${share}%.`,
    accentApart: (hex: string, share: number) => `${hex} stands apart. Use it sparingly, about ${share}%.`,
    busyBackground: (bg: string) => `${bg} is too colorful for a background. Quiet it so the loud color can pop.`,
    noPop: (loud: string, bg: string) => `${loud} isn't popping. Fix the background: move ${bg} lighter or darker.`,
    accentBlends: (accent: string, bg: string) => `${accent} blends into ${bg}. Push it darker or lighter.`,
  },
  checksCredit: 'Checks adapted from Alena Song’s free color lesson',
  checksCreditUrl: 'https://asongstudio.com/courses/free-color-lesson',
  installLabel: 'Install Chromasome',
  installTitle: 'Install Chromasome',
  installTitleIos: 'Add to your Home Screen',
  installHintAndroid: 'Opens full screen, like an app.',
  installTap: 'Tap',
  installShare: 'Share',
  installThen: 'then',
  installAddToHome: 'Add to Home Screen',
  install: 'Install',
  installDismiss: 'Don’t show this again',
  consentLabel: 'Cookie consent',
  consentText: 'Chromasome uses Google Analytics cookies to see which features get used. Is that OK?',
  consentAccept: 'Accept',
  consentDecline: 'Decline',
  privacyPolicy: 'Privacy policy',
  privacyUrl: 'https://inmydna.com/privacy',
  cookieSettings: 'Cookie settings',
  cookies: 'Cookies',
  pngEqual: 'Equal',
  pngRoles: '60·30·10',
} as const
